services:
  samba_srv:
    image: samba-server:v1.1
    container_name: my_sambasrv
    privileged: true
    restart: unless-stopped
    environment:
      - DOMAIN=MIDTOWN.LOCAL
      - DOMAIN_DC=dc=midtown,dc=local
      - DOMAIN_EMAIL=midtown.local
      - DOMAINPASS=Your_password_goes_here
      - JOIN=true
      - HOSTIP=172.29.48.10
    ports:
      - "172.29.48.10:53:53"
      - "172.29.48.10:53:53/udp"
      - "172.29.48.10:88:88"
      - "172.29.48.10:88:88/udp"
      - "172.29.48.10:123:123"
      - "172.29.48.10:123:123/udp"
      - "172.29.48.10:135:135"
      - "172.29.48.10:137-138:137-138/udp"
      - "172.29.48.10:139:139"
      - "172.29.48.10:389:389"
      - "172.29.48.10:389:389/udp"
      - "172.29.48.10:445:445"
      - "172.29.48.10:464:464"
      - "172.29.48.10:464:464/udp"
      - "172.29.48.10:636:636"
      - "172.29.48.10:1024-1044:1024-1044"
      - "172.29.48.10:3268-3269:3268-3269"
      - "172.29.48.10:49152-49172:49152-49172"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/docker/containers/samba-server/data/:/var/lib/samba
      - /data/docker/containers/samba-server/config/samba:/etc/samba/external
      - /export/storage:/export/storage
    dns:
      - 172.29.48.5
      - 172.29.48.11
    dns_search:
      - midtown.local
    dns_opt:
      - ndots:1
    extra_hosts:
      - "server01.midtown.local:172.29.48.10"
    hostname: server01
    networks:
      ipvlan_net:
        ipv4_address: 172.29.48.10

networks:
  ipvlan_net:
    driver: ipvlan
    ipam:
      config:
        - subnet: 172.29.48.0/24
          gateway: 172.29.48.1
          ip_range: 172.29.48.8/29
    driver_opts:
      parent: eth0
